server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Configuration for admin-service endpoints
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/assessment/**
        # Configuration for employee-service endpoints
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/employee/**
        # Configuration for login-service endpoints
        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/api/login/**
        # Configuration for eureka-server endpoints
        - id: eureka-primary
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        # Configuration for eureka-server css and js endpoints
        - id: eureka-primary-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route: info
  root: info





eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "ALWAYS"


