server:
  port: 0

spring:
  application:
    name: employee-service
  datasource:
    password: Emp
    url: jdbc:mysql://127.0.0.1:3306/employee_registration?user=Employee
    username: Employee
  jpa:
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

# Configuration for Resilience4j Circuit Breaker for 'employee' service
resilience4j:
  circuitbreaker:
    instances:
      admin-service:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 5
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true